name: Issue Comment

on:
  issue_comment:
    types: [created]

jobs:
  issue_comment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run script
      run: |
        # Your script here
        echo ${{ github.event.comment.body }}
        echo ${{ github.event.issue.number }}
