name: Issue Comment

on:
  issue_comment:
    types: [created]

jobs:
  issue_comment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run script
      run: |
        # Your script here
        echo ${{ github.event.comment.body }}
        echo ${{ github.event.issue.number }}
        
    - name: Write CSV file  
      run: |
          echo "${{ github.event.issue.number }},${{ github.event.issue.title }},${{ github.event.issue.body }},${{ github.event.issue.assignee.login }},${{ github.event.issue.labels[0].name}}, ${{ github.event.issue.milestone.title }}, $(TZ='Asia/Kolkata' date +"%A, %d %B %Y %T %Z") , ${{ github.event.comment.body }}, "In Progress" ">> issues.csv
    - name: Commit changes
      run: |
          git config --global user.email "anurag_verma@fosteringlinux.com"
          git config --global user.name "pratyakshchauhan"
          git add issues.csv
          git commit -m "Add file.csv"
     
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
          github_token: ${{ secrets.TOKEN }}
