name: First Cron Job

       # Controls when the workflow will run
on:
  # Triggers the workflow every 5 minutes
  schedule:
    - cron: "*/5 * * * *"

     # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Send email with attachment
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.USER_EMAIL }}
        password: ${{ secrets.USER_PASSWORD }}
        subject: Your file from the repository
        body: Here is your file from the repository
        from: ${{ secrets.USER_EMAIL }}
        to: pratyaksh_chauhan@fosteringlinux.com
        attachments: ./issues.csv  
