name: Manual workflow
on: 
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        default: v1.0.0
        required: true
jobs:
  bump-version:
    name: Bump Package Version
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Send email with attachment
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.USER_EMAIL }}
        password: ${{ secrets.USER_PASSWORD }}
        subject: Your file from the repository
        body: Here is your file from the repository
        from: ${{ secrets.USER_EMAIL }}
        to: pratyaksh_chauhan@fosteringlinux.com
        attachments: ./issues.csv 
    - name: Write Monthly CSV file
          
      run: |
          
          cat issues.csv >> MonthlyIssues.csv
    
    - name: Rewrite CSV file
      run: |
          echo ""Issue No.","Issue Name","Description","Assignee","Label","Milestone","Day","Date","Comment","Status"" > issues.csv
                
    - name: Commit changes
      run: |
          git config --global user.email "pratyaksh_chauhan@fosteringlinux.com"
          git config --global user.name "pratyakshchauhan"
          git add .
          git commit -m "Add file.csv"
     
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
          github_token: ${{ secrets.TOKEN }}      
          
                      
