on:
  issues:
    types: [opened]

jobs:
  send-notification:
    runs-on: ubuntu-latest
    env:
      SHOWDOWN_BIN: "./node_modules/.bin/showdown"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '14'
          
      - name: Install showdown package
        run: npm install showdown
        
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3.4.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: anjali_manocha@fosteringlinux.com
          password: My@family1
          subject: 'New Issue Created'
          to: anjali_manocha@fosteringlinux.com
          body: 'A new issue has been created in your repository.'
        env:
          SHOWDOWN_BIN: ${{ env.SHOWDOWN_BIN }}
          PATH: ${{ env.SHOWDOWN_BIN }}:$PATH
