name: email_sending

on:
  issues:
    types: [opened]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
          
      - name: Send email
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          RECIEVERS_MAIL: anjali_manocha@fosteringlinux.com
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          ISSUE_TITLE:  ${{ github.event.issue.title }}
          ISSUE_DESC: ${{ github.event.issue.body }}
          ISSUE_CREATOR: ${{ github.event.issue.assignee.login }}
        run: python sendmail.py
