name: email_sending

on:
  issues:
    types: [opened]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Send email
        env:
          USER_EMAIL: anjali_manocha@fosteringlinux.com
          RECIEVERS_MAIL: pratyaksh_chauhan@fosteringlinux.com
          RECIEVERS_MAIL1: anurag_verma@fosteringlinux.com
          USER_PASSWORD: My@family1
          ISSUE_TITLE:  ${{ github.event.issue.title }}
        run: python sendmail.py
