name: email_sending

on:
  issues:
    types: [opened]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      
      - name: Send email
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          RECIEVERS_MAIL: anurag_verma@fosteringlinux.com
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          ISSUE_TITLE:  ${{ github.event.issue.title }}
          ISSUE_DESC: ${{ github.event.issue.body }}
          ISSUE_CREATOR: ${{ github.event.issue.assignee.login }}
        run: python sendmail.py
      - name: Write CSV file
          
        run: |
          
          echo "${{ github.event.issue.number }},${{ github.event.issue.title }},${{ github.event.issue.body }},${{ github.event.issue.assignee.login }},${{ github.event.issue.labels[0].name}}, ${{ github.event.issue.milestone.title }}, $(TZ='Asia/Kolkata' date +"%A, %d %B %Y %T %Z"), ${{ github.event.comment.body }},"Opened" " > issues.csv

      - name: Commit changes
        run: |
          git config --global user.email "pratyaksh_chauhan@fosteringlinux.com"
          git config --global user.name "pratyakshchauhan"
          git add issues.csv
          git commit -m "Add file.csv"
     
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
